name: Update README

on:
  schedule:
    - cron: "*/30 * * * *" # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: workflows/recent-activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
